server:
  port: 10560
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankingAccount
      username: cgonzalez
      password: "Massu$2023"
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers:
      - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
